version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: macos
      MYSQL_PASSWORD: macos
      MYSQL_DATABASE: macos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - dev-network
    volumes:
      - dbdata:/var/lib/mysql
      # - ./mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    depends_on:
      - mysql
    container_name: nginx
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/nginx.Dockerfile
    environment:
      - PORT=80
    ports:
      - "80:80"
    networks:
      - dev-network

  frontend:
    depends_on:
      - mysql
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/app.Dockerfile
    environment:
      - PORT=8080
    volumes:
      - "./frontend:/app"
    #   - '/app/node_modules'
    ports:
      - "8080:8080"
    networks:
      - dev-network

  proxy:
    depends_on:
      - mysql
    container_name: proxy
    build:
      context: ./proxy
      dockerfile: ../dockerfiles/server.Dockerfile
    environment:
      - PORT=3000
    volumes:
      - "./proxy:/app"
    #   - '/app/node_modules'
    ports:
      - "5000:3000"
    networks:
      - dev-network

  graph:
    depends_on:
      - mysql
    container_name: graph
    build:
      context: ./graph
      dockerfile: ../dockerfiles/server.Dockerfile
    environment:
      - PORT=3000
    volumes:
      - "./graph:/app"
    #   - '/app/node_modules'
    ports:
      - "4000:3000"
    networks:
      - dev-network

  backend:
    depends_on:
      - mysql
    container_name: backend
    build:
      context: ./backend
      dockerfile: ../dockerfiles/server.Dockerfile
    environment:
      - PORT=3000
    volumes:
      - "./backend:/app"
    #   - '/app/node_modules'
    ports:
      - "3000:3000"
    networks:
      - dev-network

volumes:
  dbdata:
    driver: local

networks:
  dev-network:
    driver: bridge
